version: 0.0
os: linux
files:
    - source: site
      destination: /var/www/html/
hooks:
    BeforeInstall:
        - location: app-scripts/install_dependencies
          timeout: 300
          runas: root
        - location: app-scripts/start_server
          timeout: 300
          runas: root
    ApplicationStop:
        - location: app-scripts/stop_server
          timeout: 300
          runas: root
