docs_dir: docs-source
site_name: AWS Ambit Scenario Designer for Unreal Engine 4 User Guide
nav:
    - Getting Started: 
        - Welcome: index.md
        - Setup: setup.md
    - Static Obstacles:
        - Overview: spawner-parent.md
        - Spawn in Volume: spawn-in-volume.md
        - Spawn on Path: spawn-on-path.md
        - Spawn on Surface: spawn-on-surface.md
        - Spawn with Houdini Digital Assets: spawn-with-houdini.md
        - Ambit Spawner Examples: spawner-examples.md
    - Dynamic Obstacles: 
        - Overview: spawn-vehicle-path-parent.md
        - Spawn Vehicle Path: spawn-vehicle-path.md
    - City Generation:
        - Overview: city-generation.md
        - Obtaining OpenStreetMap Files: obtaining-osm.md
        - Building Generator: building-generator.md
        - Road Generator: road-generator.md
    - Weather & Time of Day FX:
        - Overview: weather.md
    - Simulation Scenarios:
        - Manual Scenario Generation: individual-scenario-generation.md
        - Automated Scenario Generation: bulk-senario-generation.md
        - Working with AWS in Ambit: aws-setup.md
    - Exporting Assets:
        - Export Map Options: map-export.md
    - APPENDIX:
        - "Appendix: Contributing to Ambit Development": appendix-contributing.md

theme: readthedocs
extra_css:
    - css/extra.css
markdown_extensions:
    - toc:
        baselevel: 1
        toc_depth: 2
        permalink: True
